### ISSUE TITLE
Mayo 01, 2020 Demo, questions, and answers.

### ISSUE THREAD

**Issue by carlosthe19916** [project-openubl/xml-sender#4]
XML Sender es un microservicio que envía tu comprobante electrónico a la SUNAT y además se encarga de persistir tus XMLs y CDRs en un storage.

- **Link de la reunión:** Eliminado
- **La transmisición será en vivo, ASEGÚRATE DE INSTALAR [Blue Jeans](https://www.bluejeans.com/downloads)** Si utilizas Chrome te recomendamos instalar la extensión para Chrome
- **Fecha:** 01 de Mayo, 20020
- **Hora:** 16:00 (GMT-5)
- **Agrega el evento a tu calendario:** [mi calendario](https://calendar.google.com/event?action=TEMPLATE&tmeid=M2JqOWJrMmhtOHUwamczZWRkbjRtM3FqamIgZ3Jva3ZtdDFidmhpMnQ5aXNpOGplbjhjMmNAZw&tmsrc=grokvmt1bvhi2t9isi8jen8c2c%40group.calendar.google.com
)

- Diapositivas: [Slides](https://docs.google.com/presentation/d/1z34zEPhdBmyINuPQRwcVahn3PAQnAZJiiDI4d7bzIIY/edit?usp=sharing)

Agenda:
- Demostración de XML Sender
- Respuestas y preguntas

>**NOTA:** Confirme sus asistencia agregando un comentario. También puedes agregar tus preguntas y durante la demostración se darán las respuestas a tus preguntas.

**Comment by manperu** [comment]
Presente. ¿ Habrá alguna forma que github envie un recordatorio a mi correo asociado a ellos?

**Comment by carlosthe19916** [comment]
> Presente. ¿ Habrá alguna forma que github envie un recordatorio a mi correo asociado a ellos?

@manperu Gracias por tu confirmación. Agrega el evento a tu calendario haciendo click en el link [mi calendario](https://calendar.google.com/event?action=TEMPLATE&tmeid=N21xY200dWlqdTBoc2Q4cW1zbnE4ZmsyMTEgY2ZlcmlhdmlAcmVkaGF0LmNvbQ&tmsrc=cferiavi%40redhat.com) de la descripción, allí podrás configurar los recordatorios (a travéz de tu cuenta de Gmail).

**Comment by elvisraul** [comment]
Presente.

**Comment by cesarvv** [comment]
Presente, estoy interesado, pero no entiendo que hace tu proyecto, genera los XML y los envía o sólo envía? Gracias

**Comment by carlosthe19916** [comment]
> Presente, estoy interesado, pero no entiendo que hace tu proyecto, genera los XML y los envía o sólo envía? Gracias

@cesarvv Buen punto. Se añadirá una pequeña seccion de la demo para dar una vista general de todos los productos de Project OpenUBL (para entender que hace cada producto), y también de la visión del proyecto.

**Comment by FerFox9** [comment]
Interesante el tema, que bondades se podrá tener con esa herramienta

**Comment by olanaso** [comment]
Presente carlitos

**Comment by carlosthe19916** [comment]
Gracias a todos por asistir

**Comment by gvaronas** [comment]
Estimados Felicitaciones por el proyecto.
Mi pregunta, ¿habrá alguna posibilidad de que en vez de enviar un XML, se envié un JSON?

**Comment by carlosthe19916** [comment]
@gvaronas Mantente alerta a las novedades de Project OpenUBL, despues de lanzar la version 1.0.0.Final de **XML Sender** se procederá a crear un proyecto que empaquete XML Sender y XML Builder en un solo lugar y podrás enviar un JSON e internamente seguirá el proceso **JSON=> XML Builder => XML Sender**, de esta forma enviarás un JSON y el resto lo hará el software
